/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserProfileRouteImport } from './routes/userProfile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistPlaylistIdRouteImport } from './routes/playlist.$playlistId'
import { Route as ArtistProfileArtistIdRouteImport } from './routes/artistProfile.$artistId'

const UserProfileRoute = UserProfileRouteImport.update({
  id: '/userProfile',
  path: '/userProfile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistPlaylistIdRoute = PlaylistPlaylistIdRouteImport.update({
  id: '/playlist/$playlistId',
  path: '/playlist/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistProfileArtistIdRoute = ArtistProfileArtistIdRouteImport.update({
  id: '/artistProfile/$artistId',
  path: '/artistProfile/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/userProfile': typeof UserProfileRoute
  '/artistProfile/$artistId': typeof ArtistProfileArtistIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/userProfile': typeof UserProfileRoute
  '/artistProfile/$artistId': typeof ArtistProfileArtistIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/userProfile': typeof UserProfileRoute
  '/artistProfile/$artistId': typeof ArtistProfileArtistIdRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/userProfile'
    | '/artistProfile/$artistId'
    | '/playlist/$playlistId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/userProfile'
    | '/artistProfile/$artistId'
    | '/playlist/$playlistId'
  id:
    | '__root__'
    | '/'
    | '/userProfile'
    | '/artistProfile/$artistId'
    | '/playlist/$playlistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserProfileRoute: typeof UserProfileRoute
  ArtistProfileArtistIdRoute: typeof ArtistProfileArtistIdRoute
  PlaylistPlaylistIdRoute: typeof PlaylistPlaylistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/userProfile': {
      id: '/userProfile'
      path: '/userProfile'
      fullPath: '/userProfile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$playlistId': {
      id: '/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof PlaylistPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artistProfile/$artistId': {
      id: '/artistProfile/$artistId'
      path: '/artistProfile/$artistId'
      fullPath: '/artistProfile/$artistId'
      preLoaderRoute: typeof ArtistProfileArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserProfileRoute: UserProfileRoute,
  ArtistProfileArtistIdRoute: ArtistProfileArtistIdRoute,
  PlaylistPlaylistIdRoute: PlaylistPlaylistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
